# =====================================================================
# Feature file — generated by requirements-to-bdd
# Source requirement(s): FR-<n>            (see ../docs/discovery/<initiative>/requirements.md)
# Wireframe screen:       <screen / frame name> — <path or Figma link>
# Applicable NFRs:        <e.g. accessibility (minimal baseline); fare quote < 2s>
# Priority:               Must | Should | Could
# Status:                 Draft — awaiting verification
# =====================================================================

@FR-<n> @<priority> @screen-flight-search
Feature: Search for flights
  As a leisure traveller
  I want to search flights for my dates and route
  So that I can choose a fare and book

  Background:
    Given I am on the flight search screen

  # AC: results are shown for a valid search
  Scenario: Traveller searches a valid route and sees fares
    Given a route and dates with available flights
    When I search
    Then I see a list of fares ordered by price
    And each fare shows price, times, and stops

  # Wireframe state: empty
  Scenario: No flights for the search
    Given a route and dates with no available flights
    When I search
    Then I am told no flights match and offered to change my dates

  # Travel edge case: price/availability can change between search and select
  Scenario: Fare price changed since the search
    Given I selected a fare from the results
    When the fare is re-validated before booking and the price has changed
    Then I am shown the new price and asked to confirm before continuing

  # Data variations
  Scenario Outline: Search by cabin and passengers
    When I search "<cabin>" for "<pax>" passengers
    Then the fares shown are for "<cabin>" and priced for "<pax>" passengers

    Examples:
      | cabin    | pax |
      | Economy  | 1   |
      | Economy  | 3   |
      | Business | 2   |

# ---------------------------------------------------------------------
# Traceability: every Scenario maps to an AC in FR-<n> or a wireframe state.
# Note the re-validate-before-confirm scenario — a real travel rule, not invented.
# ---------------------------------------------------------------------
